const REDUCER = {
    CATEGORY_SELECTION: "CATEGORY_SELECTION",
    UPDATE_CART: "UPDATE_CART",
    UPDATE_NOTIFICATION: 'UPDATE_NOTIFICATION',
    UPDATE_RESOLUTION: 'UPDATE_RESOLUTION'
}

export default REDUCER;